import type { AppUser } from '@/types/auth'
import type { AuditTask } from '@/types/task'
import type { AuditResult, AuditExportData } from '@/types/audit'
import { Timestamp } from 'firebase/firestore'

const now = Timestamp.now()
const yesterday = Timestamp.fromMillis(Date.now() - 86400000)
const twoDaysAgo = Timestamp.fromMillis(Date.now() - 172800000)
const threeDaysAgo = Timestamp.fromMillis(Date.now() - 259200000)
const weekAgo = Timestamp.fromMillis(Date.now() - 604800000)

export const DEMO_USER: AppUser = {
  uid: 'demo-supervisor-001',
  email: 'admin@demo.com',
  displayName: 'Carlos Martinez',
  role: 'supervisor',
  createdAt: weekAgo,
  lastLoginAt: now,
}

export const DEMO_TASKS: AuditTask[] = [
  {
    id: 'task-001',
    title: 'Auditoria Pasillo A - Zona Norte',
    warehouseLocation: 'Almacen Central CDMX',
    aisle: 'A1',
    positionRange: { from: 'A01', to: 'A15' },
    config: {
      storageType: 'racks',
      rowSize: 6,
      columnSize: 12,
      idLength: 10,
      locationName: 'Zona Norte',
    },
    status: 'completed',
    createdBy: 'demo-supervisor-001',
    assignedTo: 'operador-001',
    createdAt: threeDaysAgo,
    updatedAt: yesterday,
    completedAt: yesterday,
    validatedAt: null,
    auditResultId: 'audit-001',
    notes: 'Revisar especialmente posiciones A05-A10, se reportaron movimientos no registrados.',
  },
  {
    id: 'task-002',
    title: 'Revision Pasillo B - Racks Altos',
    warehouseLocation: 'Almacen Central CDMX',
    aisle: 'B2',
    positionRange: { from: 'B01', to: 'B20' },
    config: {
      storageType: 'racks',
      rowSize: 8,
      columnSize: 15,
      idLength: 10,
      locationName: 'Zona Sur',
    },
    status: 'in_progress',
    createdBy: 'demo-supervisor-001',
    assignedTo: 'operador-002',
    createdAt: twoDaysAgo,
    updatedAt: now,
    completedAt: null,
    validatedAt: null,
    auditResultId: null,
    notes: '',
  },
  {
    id: 'task-003',
    title: 'Cotejo Estantes Zona de Picking',
    warehouseLocation: 'Almacen Monterrey',
    aisle: 'C1',
    positionRange: { from: 'C01', to: 'C08' },
    config: {
      storageType: 'shelves',
      rowSize: 4,
      columnSize: 10,
      idLength: 8,
      locationName: 'Picking Area',
    },
    status: 'created',
    createdBy: 'demo-supervisor-001',
    assignedTo: null,
    createdAt: now,
    updatedAt: now,
    completedAt: null,
    validatedAt: null,
    auditResultId: null,
    notes: 'Tarea urgente - inventario trimestral',
  },
  {
    id: 'task-004',
    title: 'Auditoria Pasillo D - Zona Frio',
    warehouseLocation: 'Almacen Central CDMX',
    aisle: 'D1',
    positionRange: { from: 'D01', to: 'D12' },
    config: {
      storageType: 'racks',
      rowSize: 5,
      columnSize: 10,
      idLength: 10,
      locationName: 'Zona Refrigerada',
    },
    status: 'validated',
    createdBy: 'demo-supervisor-001',
    assignedTo: 'operador-001',
    createdAt: weekAgo,
    updatedAt: threeDaysAgo,
    completedAt: threeDaysAgo,
    validatedAt: twoDaysAgo,
    auditResultId: 'audit-002',
    notes: 'Completada sin incidencias mayores.',
  },
  {
    id: 'task-005',
    title: 'Revision Piso Zona de Embarques',
    warehouseLocation: 'Almacen Guadalajara',
    aisle: 'E1',
    positionRange: { from: 'E01', to: 'E06' },
    config: {
      storageType: 'floor',
      rowSize: 3,
      columnSize: 8,
      idLength: 12,
      locationName: 'Embarques',
    },
    status: 'assigned',
    createdBy: 'demo-supervisor-001',
    assignedTo: 'operador-003',
    createdAt: yesterday,
    updatedAt: yesterday,
    completedAt: null,
    validatedAt: null,
    auditResultId: null,
    notes: 'Operador asignado: Juan Lopez',
  },
]

export const DEMO_AUDIT_RESULTS: AuditResult[] = [
  {
    id: 'audit-001',
    taskId: 'task-001',
    exportDataPath: 'audits/audit-001/export-data.json',
    metadata: {
      auditId: 'AUD-2026-0301',
      taskId: 'task-001',
      operatorId: 'operador-001',
      operatorName: 'Miguel Angel Reyes',
      startedAt: '2026-03-08T09:00:00Z',
      completedAt: '2026-03-08T11:45:00Z',
      droneModel: 'DJI Matrice 350 RTK',
      softwareVersion: '2.4.1',
      warehouseLocation: 'Almacen Central CDMX',
      aisle: 'A1',
      positionRange: { from: 'A01', to: 'A15' },
      config: {
        storageType: 'racks',
        rowSize: 6,
        columnSize: 12,
        idLength: 10,
        locationName: 'Zona Norte',
      },
    },
    summary: {
      totalPositionsScanned: 180,
      totalItemsDetected: 156,
      totalDiscrepancies: 8,
      scanDurationMinutes: 165,
      coveragePercent: 96,
    },
    discrepancySummary: {
      total: 8,
      bySeverity: { low: 2, medium: 3, high: 2, critical: 1 },
      byType: {
        missing_item: 3,
        extra_item: 1,
        wrong_position: 2,
        wrong_quantity: 1,
        damaged: 1,
        id_mismatch: 0,
      },
    },
    status: 'pending_review',
    reviewedBy: null,
    reviewedAt: null,
    validatedBy: null,
    validatedAt: null,
    reviewNotes: '',
    uploadedAt: yesterday,
  },
  {
    id: 'audit-002',
    taskId: 'task-004',
    exportDataPath: 'audits/audit-002/export-data.json',
    metadata: {
      auditId: 'AUD-2026-0228',
      taskId: 'task-004',
      operatorId: 'operador-001',
      operatorName: 'Miguel Angel Reyes',
      startedAt: '2026-03-05T08:30:00Z',
      completedAt: '2026-03-05T10:15:00Z',
      droneModel: 'DJI Matrice 350 RTK',
      softwareVersion: '2.4.1',
      warehouseLocation: 'Almacen Central CDMX',
      aisle: 'D1',
      positionRange: { from: 'D01', to: 'D12' },
      config: {
        storageType: 'racks',
        rowSize: 5,
        columnSize: 10,
        idLength: 10,
        locationName: 'Zona Refrigerada',
      },
    },
    summary: {
      totalPositionsScanned: 60,
      totalItemsDetected: 58,
      totalDiscrepancies: 2,
      scanDurationMinutes: 105,
      coveragePercent: 100,
    },
    discrepancySummary: {
      total: 2,
      bySeverity: { low: 1, medium: 1, high: 0, critical: 0 },
      byType: {
        missing_item: 1,
        extra_item: 0,
        wrong_position: 1,
        wrong_quantity: 0,
        damaged: 0,
        id_mismatch: 0,
      },
    },
    status: 'validated',
    reviewedBy: 'demo-supervisor-001',
    reviewedAt: threeDaysAgo,
    validatedBy: 'demo-supervisor-001',
    validatedAt: twoDaysAgo,
    reviewNotes: 'Auditoria correcta, discrepancias menores corregidas en WMS.',
    uploadedAt: threeDaysAgo,
  },
]

function generateItems() {
  const statuses = ['found', 'found', 'found', 'found', 'found', 'found', 'found', 'found', 'missing', 'unexpected', 'damaged', 'misplaced'] as const
  const items = []
  for (let rack = 1; rack <= 3; rack++) {
    for (let row = 1; row <= 6; row++) {
      for (let col = 1; col <= 12; col++) {
        if (Math.random() > 0.87) continue
        const status = statuses[Math.floor(Math.random() * statuses.length)]
        items.push({
          itemId: `SKU-${String(rack).padStart(2, '0')}${String(row).padStart(2, '0')}${String(col).padStart(2, '0')}${String(Math.floor(Math.random() * 9000) + 1000)}`,
          position: `R${String(rack).padStart(2, '0')}-A${String(row).padStart(2, '0')}-C${String(col).padStart(2, '0')}`,
          rack: `R${String(rack).padStart(2, '0')}`,
          row,
          column: col,
          status,
          confidence: status === 'found' ? 0.92 + Math.random() * 0.08 : 0.65 + Math.random() * 0.25,
          detectedAt: new Date(Date.now() - Math.random() * 10000000).toISOString(),
          imageRef: null,
          notes: status === 'damaged' ? 'Etiqueta parcialmente danada' : '',
        })
      }
    }
  }
  return items
}

function generateDiscrepancies() {
  return [
    {
      id: 'disc-001',
      type: 'missing_item' as const,
      severity: 'critical' as const,
      itemId: 'SKU-0103051234',
      expectedPosition: 'R01-A03-C05',
      actualPosition: null,
      expectedQuantity: 1,
      actualQuantity: 0,
      description: 'Item de alto valor no encontrado en posicion esperada. Verificar traslados recientes.',
      resolved: false,
      resolvedBy: null,
      resolvedAt: null,
      resolutionNotes: null,
    },
    {
      id: 'disc-002',
      type: 'wrong_position' as const,
      severity: 'high' as const,
      itemId: 'SKU-0205083456',
      expectedPosition: 'R02-A05-C08',
      actualPosition: 'R02-A05-C10',
      expectedQuantity: 1,
      actualQuantity: 1,
      description: 'Item encontrado 2 columnas a la derecha de su posicion registrada.',
      resolved: false,
      resolvedBy: null,
      resolvedAt: null,
      resolutionNotes: null,
    },
    {
      id: 'disc-003',
      type: 'extra_item' as const,
      severity: 'medium' as const,
      itemId: 'SKU-0301027890',
      expectedPosition: null,
      actualPosition: 'R03-A01-C02',
      expectedQuantity: 0,
      actualQuantity: 1,
      description: 'Item detectado sin registro previo en el sistema. Posible ingreso no registrado.',
      resolved: false,
      resolvedBy: null,
      resolvedAt: null,
      resolutionNotes: null,
    },
    {
      id: 'disc-004',
      type: 'missing_item' as const,
      severity: 'high' as const,
      itemId: 'SKU-0104091111',
      expectedPosition: 'R01-A04-C09',
      actualPosition: null,
      expectedQuantity: 1,
      actualQuantity: 0,
      description: 'Item no detectado. Ultima actualizacion en WMS hace 15 dias.',
      resolved: false,
      resolvedBy: null,
      resolvedAt: null,
      resolutionNotes: null,
    },
    {
      id: 'disc-005',
      type: 'damaged' as const,
      severity: 'medium' as const,
      itemId: 'SKU-0206112222',
      expectedPosition: 'R02-A06-C11',
      actualPosition: 'R02-A06-C11',
      expectedQuantity: 1,
      actualQuantity: 1,
      description: 'Etiqueta de codigo de barras danada, lectura parcial. Requiere re-etiquetado.',
      resolved: false,
      resolvedBy: null,
      resolvedAt: null,
      resolutionNotes: null,
    },
    {
      id: 'disc-006',
      type: 'wrong_quantity' as const,
      severity: 'medium' as const,
      itemId: 'SKU-0302043333',
      expectedPosition: 'R03-A02-C04',
      actualPosition: 'R03-A02-C04',
      expectedQuantity: 3,
      actualQuantity: 1,
      description: 'WMS indica 3 unidades, solo se detecto 1. Verificar salidas no registradas.',
      resolved: false,
      resolvedBy: null,
      resolvedAt: null,
      resolutionNotes: null,
    },
    {
      id: 'disc-007',
      type: 'wrong_position' as const,
      severity: 'low' as const,
      itemId: 'SKU-0103074444',
      expectedPosition: 'R01-A03-C07',
      actualPosition: 'R01-A03-C08',
      expectedQuantity: 1,
      actualQuantity: 1,
      description: 'Item desplazado una columna. Posible error de acomodo.',
      resolved: true,
      resolvedBy: 'demo-supervisor-001',
      resolvedAt: '2026-03-09T14:00:00Z',
      resolutionNotes: 'Corregido en WMS, item reubicado fisicamente.',
    },
    {
      id: 'disc-008',
      type: 'missing_item' as const,
      severity: 'low' as const,
      itemId: 'SKU-0205125555',
      expectedPosition: 'R02-A05-C12',
      actualPosition: null,
      expectedQuantity: 1,
      actualQuantity: 0,
      description: 'Item de bajo valor no localizado. Posiblemente dado de baja sin actualizar sistema.',
      resolved: true,
      resolvedBy: 'demo-supervisor-001',
      resolvedAt: '2026-03-09T15:30:00Z',
      resolutionNotes: 'Confirmado: item fue desechado por dano. WMS actualizado.',
    },
  ]
}

export const DEMO_FULL_AUDIT_DATA: AuditExportData = {
  version: '1.0.0',
  metadata: DEMO_AUDIT_RESULTS[0].metadata,
  summary: DEMO_AUDIT_RESULTS[0].summary,
  items: generateItems(),
  discrepancies: generateDiscrepancies(),
  backups: [
    {
      type: 'video',
      filename: 'vuelo-pasillo-A1.mp4',
      storagePath: 'audits/audit-001/videos/vuelo-pasillo-A1.mp4',
      sizeBytes: 524288000,
      uploadedAt: '2026-03-08T12:00:00Z',
      checksum: 'abc123def456',
    },
    {
      type: 'log',
      filename: 'flight-log-20260308.json',
      storagePath: 'audits/audit-001/backups/flight-log-20260308.json',
      sizeBytes: 2048000,
      uploadedAt: '2026-03-08T12:01:00Z',
      checksum: 'def789ghi012',
    },
  ],
}
